3 add content pages to flet web app
christophschaller/metriker pull request #15
Opened 2023-03-31 08:46 UTC by davidbuu

Hey CHris, segne das mal ab!

2023-03-31 18:42 UTC, christophschaller requested changes

2023-03-31 18:42 UTC, christophschaller commented on metriker_app/metriker_app/views/challenges_view.py
> +            print(distance)
No print statements in final code

2023-04-12 17:06 UTC, davidbuu commented on metriker_app/metriker_app/views/challenges_view.py
> +class ChallengeContent(ft.Column):
Noch offen

2023-04-24 15:00 UTC, davidbuu commented
Alle change requests sind eingebaut.

2023-04-24 15:02 UTC, davidbuu commented
Muss ich den Pull request wieder anstossen? Wenn ja wie? Finde keinen Button der dazu einlädt?

2025-02-26 16:04 UTC, closed without merging